name: kirkanen-phonebook-dev

services:
  app:
    image: frontend-phonebook-dev
    container_name: frontend-phonebook-dev
    build:
      context: .
      dockerfile: ./frontend/dev.Dockerfile
    env_file:
      - frontend/.env
    volumes:
      - ./frontend/:/usr/src/app
  server:
    image: express-server-phonebook
    container_name: express-server-phonebook-dev
    build:
      context: .
      dockerfile: ./backend/dev.Dockerfile
    env_file:
      - backend/.env
    volumes:
      - ./backend/:/usr/src/app

  nginx:
    image: nginx:1.20.1
    container_name: reverse-proxy-dev
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - app
      - server
