services:
  # server:
  #   image: express-server
  #   build: .
  #   ports:
  #     - 3000:3000
  #   # env_file: ".env"
  #   environment:
  #     - REDIS_URL=redis://default:password@redis:6379
  #     - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data:/data/db
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - 6379:6379
    expose:
      - 6379
    command: ['redis-server', '/etc/redis/redis.conf', '--appendonly', 'yes']
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./redis_data:/data

volumes:
  mongo_data:
  redis_data:

